# Generated by Django 4.2 on 2024-03-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='123', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Coordinador'), (3, 'Profesor')], default=3),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=245, unique=True),
        ),
    ]
